"""init_db

Revision ID: 09997995982c
Revises: c7992a03a94c
Create Date: 2025-08-16 12:00:55.471143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09997995982c'
down_revision: Union[str, Sequence[str], None] = 'c7992a03a94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especimes',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=11), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('conservacao', sa.String(length=11), nullable=False),
    sa.Column('catalogado_em', sa.DateTime(), nullable=False),
    sa.Column('taxon_id', sa.Integer(), nullable=False),
    sa.Column('museu_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['museu_id'], ['museus.pk_id'], ),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxons.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('codigo')
    )
    op.drop_table('especimes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especimes',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('apelido', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('altura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('conservacao', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('catalogado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('taxon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('museu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['museu_id'], ['museus.pk_id'], name=op.f('especimes_museu_id_fkey')),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxons.pk_id'], name=op.f('especimes_taxon_id_fkey')),
    sa.PrimaryKeyConstraint('pk_id', name=op.f('especimes_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('especimes_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('especimes')
    # ### end Alembic commands ###
