"""init_db

Revision ID: 66bee7f3c80a
Revises: 09997995982c
Create Date: 2025-08-16 12:22:52.547503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bee7f3c80a'
down_revision: Union[str, Sequence[str], None] = '09997995982c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('museus', sa.Column('estado', sa.String(length=15), nullable=False))
    op.drop_column('museus', 'pais')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('museus', sa.Column('pais', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_column('museus', 'estado')
    # ### end Alembic commands ###
